logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://localhost:9090/eureka/
    availability-zones:
      region1: zone1
      
spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password: null
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  h2.console:
    enabled: true
    path: /h2-console
  cloud:
    gateway:
      routes:
      - id: service1
        uri: lb://service1
        predicates:
        - Path=/service1/test1/**
        - Method=GET
        filters:
        - RemoveRequestHeader=Cookie
        - name: Retry
          args:
            retries: 2
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/inCaseOfFailureUseThis
      - id: tokenValidate
        uri: http://httpbin.org/get
        predicates:
        - Path=/get
        filters:
        - name: Retry
          args:
            retries: 2
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/inCaseOfFailureUseThis