server:
  port: 8081
  servlet:    context-path: /service1
spring:
  application:
    name: service1
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://localhost:9090/eureka/
    availability-zones:
      region1: zone1
